MIN_SPRINT_RACE_DURATION = 5
MAX_SPRINT_RACE_DURATION = 60
MIN_LAP_TIME_SEC = 80
MAX_LAP_TIME_SEC = 840 #15 mins
MIN_FUEL_PER_LAP = 0.5
MAX_FUEL_PER_LAP = 15
MAX_FUEL_CAPACITY = 120
SECONDS_IN_MINUTE = 60